### PR TITLE
Feature/progresschart

### PR DESCRIPTION
**Pull request by harshiKTH**

### CODE REVIEW

**Comment by saranyas72** [comment]
There are conflicts with the working code in master. Please resolve the conflicts and re-send the code.

**Comment by harshiKTH** [comment]
Hello Saranya

I cannot do anything since Dimitrios has changed the design. so I don't use
my code any more.😃

**Comment by saranyas72** [comment]
As Harshi said, the code will not be used anymore so the code change will not be approved. This change cannot be merged into the master.

**Review by saranyas72 — CHANGES_REQUESTED** [review]
The pull request cannot be approved to be merged into the master.

**Pull request closed without merging**
